development:
  adapter: postgresql
  encoding: unicode
  database: learning_tool_development
  pool: 5
  username: rails
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: learning_tool_development
  pool: 5
  username: rails
  password:
