#PostgreSQL configuration

production:
  adapter: postgresql
  encoding: unicode
  database: learning_tool_development
  pool: 5
  username: rails_learning_tool
  password: Figaro.env.postgresql_password

development:
  adapter: postgresql
  encoding: unicode
  database: learning_tool_development
  pool: 5
  username: rails
  password: Figaro.env.postgresql_password

test:
  adapter: postgresql
  encoding: unicode
  database: learning_tool_development
  pool: 5
  username: rails
  password: Figaro.env.postgresql_password
